CREATE OR REPLACE TABLE HOTELS (
    id STRING NOT NULL,
    hotelbrandname VARCHAR(512) NOT NULL,
    hotelfullyqualifiedname VARCHAR(512) NOT NULL,
    hotelcountry VARCHAR(100) NOT NULL,
    hotelprovince VARCHAR(2) NOT NULL,
    hotelstreetnumber INTEGER NOT NULL,
    hotelstreetname VARCHAR(512) NOT NULL,
    hotelcity VARCHAR(100) NOT NULL,
    hotelpostalcode VARCHAR(10) NOT NULL,
    phonenum INTEGER,
    website STRING NOT NULL,
    "description" STRING,
    servicelevel VARCHAR(100) NOT NULL,
    bar_lounge BOOLEAN DEFAULT false,
    breakfast_included BOOLEAN DEFAULT false,
    business_center BOOLEAN DEFAULT false,
    cold_weather_service BOOLEAN DEFAULT false,
    dry_cleaning_service BOOLEAN DEFAULT false,
    electric_vehicle_charging BOOLEAN DEFAULT false,
    executive_lounge BOOLEAN DEFAULT false,
    gift_shop BOOLEAN DEFAULT false,
    kids_club BOOLEAN DEFAULT false,
    laundry_self BOOLEAN DEFAULT false,
    meeting_event_space BOOLEAN DEFAULT false,
    outdoor_patio BOOLEAN DEFAULT false,
    parking_self BOOLEAN DEFAULT false,
    parking_valet BOOLEAN DEFAULT false,
    pets_allowed BOOLEAN DEFAULT false,
    "pool" BOOLEAN DEFAULT false,
    restaurant BOOLEAN DEFAULT false,
    room_service BOOLEAN DEFAULT false,
    spa BOOLEAN DEFAULT false,
    swimming_pool_indoor BOOLEAN DEFAULT false,
    swimming_pool_outdoor BOOLEAN DEFAULT false,
    wheelchair_accessible BOOLEAN DEFAULT false,
    kitchen BOOLEAN DEFAULT false,
    microwave_and_refridgerator BOOLEAN DEFAULT false,
    outdoor_recreation BOOLEAN DEFAULT false,
    maxoccupancy INTEGER NOT NULL,
    operationalrooms INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE ACCOMMODATIONS (
    id STRING NOT NULL,
    hotel_id STRING NOT NULL,
    accommodationtype VARCHAR(5) NOT NULL,
    "description" STRING,
    squarefootage INTEGER NOT NULL,
    maxoccupancy INTEGER NOT NULL,
    numbeds INTEGER NOT NULL,
    bedsize VARCHAR(10) NOT NULL,
    roomnumber INTEGER NOT NULL,
    rooomfloor INTEGER NOT NULL,
    ameneties STRING,
    occupied BOOLEAN DEFAULT false,
    rate FLOAT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (hotel_id) REFERENCES HOTELS(id) ON DELETE CASCADE
);

CREATE OR REPLACE TABLE REVIEWS (
    id STRING NOT NULL,
    hotel_id STRING NOT NULL,
    reviewdate DATETIME NOT NULL,
    reviewedby STRING,
    travelledfrom STRING,
    travelcompanions STRING,
    typeoftrip STRING,
    title VARCHAR(144) NOT NULL,
    feedback STRING,
    roomcomfort INTEGER NOT NULL,
    roomcleanliness INTEGER NOT NULL,
    staffservice INTEGER NOT NULL,
    facilities INTEGER NOT NULL,
    "value" INTEGER NOT NULL,
    appropriate BOOLEAN DEFAULT true,
    PRIMARY KEY (id),
    FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE
);

CREATE OR REPLACE TABLE TRANSACTIONS (
    id STRING NOT NULL,
    hotel_id STRING NOT NULL,
    accommodation_id STRING NOT NULL,
    checkindate DATETIME NOT NULL,
    checkoutdate DATETIME NOT NULL,
    methodofpayment VARCHAR(100) NOT NULL,
    saleamount FLOAT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (hotel_id) REFERENCES HOTELS(id) ON DELETE CASCADE,
    FOREIGN KEY (accommodation_id) REFERENCES ACCOMMODATIONS(id) ON DELETE CASCADE
);